### ISSUE TITLE
Encrypted keyring

### ISSUE THREAD

**Issue by jesusgt** [r-darwish/pushbullet-cli#19]
Hi there;
I was using the original release and have upgraded just now.
I've noticed that the script now asks "Please enter password for encrypted keyring:" with every push.
Is this the normal behaviour? as I do not want to be asked for the password every time.
Thanks

**Comment by r-darwish** [comment]
Hello,

You're probably using a Linux without a desktop environment. In this scenario, the [keyring](https://pypi.python.org/pypi/keyring) module looks for the pycrypto module. If that module is installed, the keyring module creates an encrypted keyring using that pycrypto, which requires you to enter your password every time you wish to access it. Like you, I think that this is quite a stupid default behaviour. The solution is to put a [configuration file](https://gist.github.com/r-darwish/d9c5f29cc00f660508c8) for the keyring module that instruct it to use the unencrypted key ring.

On Windows, OS X and Linux with a desktop environment, Pushbullet CLI should use the system keyring.

I'll add this to the README file soon.

**Comment by jesusgt** [comment]
You're right I am using a headless Ubuntu server, CLI only.
Thanks very much for your temporary solution. Much appreciated.

**Comment by r-darwish** [comment]
Should be fixed in the next version even without a configuration file
