### ISSUE TITLE
Feature request: Pull support

### ISSUE THREAD

**Issue by siddharthist** [r-darwish/pushbullet-cli#24]
On the website and Firefox extension, I can access notifications, SMS messages, etc. from other devices. Is it possible to support that here?

**Comment by r-darwish** [comment]
I guess this is possible, but I personally don't see how dumping all of the notifications to a terminal more useful then the web extensions that have real time notifications. I'll leave this open to see if more people are interested in this feature.

**Comment by siddharthist** [comment]
Perhaps a more general task would be to create a Python library with support for both the push/pull parts of the API, and have the cli as an executable wrapper on top of that library.

**Comment by r-darwish** [comment]
This is actually the way things implemented now. This project wraps https://github.com/randomchars/pushbullet.py

**Comment by siddharthist** [comment]
Oh, thanks for clarifying that!
