### ISSUE TITLE
Impossible to send title with a note

### ISSUE THREAD

**Issue by ManuCart** [r-darwish/pushbullet-cli#28]
with
```
pb push "I love burritos"
````

It's not possible to send title, it's just the body

I found in the API to push a note we can do send title and body
- title : The note's title.
- body : The note's message.

I need to send the title too

**Comment by shruthinayak** [comment]
Hi @ManuCart 
Could you elaborate on the issue? 
I was able to push a note with title and body using `pb push --title "Hello" "What's up"`
Am I missing something? Sorry if I got your question wrong. I'm a beginner and trying to understand how open source contributions work. :)

**Comment by ManuCart** [comment]
Hi,
Thanks for your help. It's working.
I don't know why but I didn't found it he docs.
