### ISSUE TITLE
Cron pb push

### ISSUE THREAD

**Issue by jadsaffar** [r-darwish/pushbullet-cli#29]
could pb push run in cron?

**Comment by r-darwish** [comment]
I don't see why not. You can either specify the pushbullet key in an environment variable, or run `pb set-key` as root

**Comment by jadsaffar** [comment]
i am trying to run this and nothing is happening when the port is not listening.
i does work when i run it in the command line but not as a cron job

/usr/sbin/lsof -i :9091 | /usr/bin/grep LISTEN || /usr/local/bin/pb push "Transmission Down..."

**Comment by r-darwish** [comment]
Does `pb` work when you run it as the root user?
