### ISSUE TITLE
pb push fails when no message is given. 

### ISSUE THREAD

**Issue by shruthinayak** [r-darwish/pushbullet-cli#30]
Hello, 
I really loved this tool. I played with it for a while. This is what I encountered. 

- The tool doesn't send the message after reading one or multiple lines of input. I have attached a screenshot of the problem I faced. 
![image](https://cloud.githubusercontent.com/assets/1544918/14660063/19f9ed4a-0667-11e6-9381-146b903a8a2d.png)
- Also, echo "Hello" | pb push sends an empty push with title "Note" and empty body.
I might be wrong. @r-darwish Could you please take a look at it? 
Also, I would love to contribute. In case if this is a legitimate issue, may I work on this?

Thank you.

**Comment by r-darwish** [comment]
Ctrl+C terminates the program. Ctrl+D should work

**Comment by tbolisetty** [comment]
Hi @r-darwish , Ctrl+D doesn't send any push message, but while trying Ctrl+Z terminates the command and sends an empty push "Note".
![capture](https://cloud.githubusercontent.com/assets/8852272/14765676/35d0f958-09b1-11e6-9ca4-c5940b13f4aa.PNG)

**Comment by r-darwish** [comment]
Should be fixed in version 0.7.5. Thanks for reporting
