### ISSUE TITLE
Upload the app to PyPI

### ISSUE THREAD

**Issue by r-darwish** [r-darwish/pushbullet-cli#9]
I would be great if you upload the app to PyPI. Since you're the author then you should be the one doing it.

**Comment by EvanHahn** [comment]
I've never done this before—is there a guide/tutorial you recommend?

**Comment by r-darwish** [comment]
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by EvanHahn** [comment]
I'll do this soon.

**Comment by EvanHahn** [comment]
@r-darwish Deferring to you on this!

**Comment by r-darwish** [comment]
https://pypi.python.org/pypi/pushbullet-cli/0.1
